spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/archive
        username: postgres
        password: root
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: true
server:
    address: localhost
    port: 3000