spring:
    datasource:
        url: jdbc:postgresql://10.3.0.101:5432/archive
        username: postgres
        password: password
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
        show-sql: true
