spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/archive
        username: postgres
        password: root
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                generate_statistics: true
                id.new_generator_mappings: true
                jdbc:
                    batch_size: 20
                    fetch_size: 20
                order_inserts: true
                order_updates: true
logging:
    level:
        example.archive: trace
        org.hibernate:
            SQL: debug
            type: trace
server:
    port: 3001
